import webapp2
import logging

from models.user import User
from models.media import Media

class Handler(webapp2.RequestHandler):
    def get(self, username, kind='all', element_to_style='self'):
        need_anime = (kind == 'all' or kind == 'anime')
        need_manga = (kind == 'all' or kind == 'manga')

        user = User.all().filter('username =', username).get()
        if user is None:
            # User doesn't exist so schedule them to be scraped later
            logging.info('User "' + username + '" does not exist in database')
            user = User(username=username, scrape_anime=need_anime, scrape_manga=need_manga)
            user.put()

            self.generateEmptyResponse()
        else:
            # User exists so generate their CSS
            self.generateCSS(username, need_anime, need_manga)

    def generateHeading(self):
        self.response.out.write('/* This file was generated by https://github.com/Trinovantes/MyAnimeList-CSS-Generator */')
        self.response.headers['Content-Type'] = 'text/css'

    def generateEmptyResponse(self):
        self.generateHeading()

    def generateCSS(self, username, need_anime, need_manga):
        self.generateHeading()
