from flask import abort

from models.media import Media

class Generator():
    def __init__(self, medium_type, element_to_style):
        self.response_body    = ''
        self.medium_type      = medium_type
        self.element_to_style = element_to_style
        self.__validate_input()

    def generate(self):
        yield "/* This file was generated by https://github.com/Trinovantes/MyAnimeList-Cover-CSS-Generator */\n\n"
        
        media_items = Media.select()
        if self.medium_type != 'all':
            media_items = media_items.where(Media.medium_type == self.medium_type)

        if self.element_to_style == 'self':
            pseudo_selector = ""
        elif self.element_to_style == 'before':
            pseudo_selector = ":before"
        elif self.element_to_style == 'after':
            pseudo_selector = ":after"

        for item in media_items:
            css_rule = ""
            if self.element_to_style == 'more':
                css_rule += "#more" + str(item.mal_id)
            else:
                css_rule += ".animetitle" # Luckily even mangas' <a> tags use the .animetitle css class
                css_rule += "[href^='/" + item.medium_type + "/" + str(item.mal_id) + "/']" + pseudo_selector

            css_rule += "{background-image:url(" + item.img_url + ");}"
            yield css_rule

    def __validate_input(self):
        if self.medium_type != 'all' and \
           self.medium_type != 'anime' and \
           self.medium_type != 'manga':
            abort(400)

        if self.element_to_style != 'self' and \
           self.element_to_style != 'before' and \
           self.element_to_style != 'after' and \
           self.element_to_style != 'more':
            abort(400)

        if self.element_to_style == 'more' and self.medium_type == 'all':
            abort(400)
